import com.sun.xml.internal.bind.v2.model.core.NonElement;

import java.net.MalformedURLException;
import java.util.Random;

public class Main {
    public static Type Normal = new Type("Normal");
    public static Type Fire = new Type("Fire");
    public static Type Water = new Type("Water");
    public static Type Grass = new Type("Grass");
    public static Type Flying = new Type("Flying");
    public static Type Fighting = new Type("Fighting");
    public static Type Poison = new Type("Poison");
    public static Type Electric = new Type("Electric");
    public static Type Ground = new Type("Ground");
    public static Type Rock = new Type("Rock");
    public static Type Psychic = new Type("Psychic");
    public static Type Ice = new Type("Ice");
    public static Type Bug = new Type("Bug");
    public static Type Ghost = new Type("Ghost");
    public static Type Steel = new Type("Steel");
    public static Type Dragon = new Type("Dragon");
    public static Type Dark = new Type("Dark");
    public static Type Fairy = new Type("Fairy");
    public static Type None = new Type();

    public static Pokemon Bulbasaur;
    public static Pokemon Ivysaur;
    public static Pokemon Venusaur;
    public static Pokemon Charmander;
    public static Pokemon Charmeleon;
    public static Pokemon Charizard;
    public static Pokemon Squirtle;
    public static Pokemon Wartortle;
    public static Pokemon Blastoise;
    public static Pokemon Caterpie;
    public static Pokemon Metapod;
    public static Pokemon Butterfree;
    public static Pokemon Weedle;
    public static Pokemon Kakuna;
    public static Pokemon Beedrill;
    public static Pokemon Pidgey;
    public static Pokemon Pidgeotto;
    public static Pokemon Pidgeot;
    public static Pokemon Rattata;
    public static Pokemon Raticate;
    public static Pokemon Spearow;
    public static Pokemon Fearow;
    public static Pokemon Ekans;
    public static Pokemon Arbok;
    public static Pokemon Pikachu;
    public static Pokemon Raichu;
    public static Pokemon Sandshrew;
    public static Pokemon Sandslash;
    public static Pokemon NidoranF;
    public static Pokemon Nidorina;
    public static Pokemon Nidoqueen;
    public static Pokemon NidoranM;
    public static Pokemon Nidorino;
    public static Pokemon Nidoking;
    public static Pokemon Clefairy;
    public static Pokemon Clefable;
    public static Pokemon Vulpix;
    public static Pokemon Ninetales;
    public static Pokemon Jigglypuff;
    public static Pokemon Wigglytuff;
    public static Pokemon Zubat;
    public static Pokemon Golbat;
    public static Pokemon Oddish;
    public static Pokemon Gloom;
    public static Pokemon Vileplume;
    public static Pokemon Paras;
    public static Pokemon Parasect;
    public static Pokemon Venonat;
    public static Pokemon Venomoth;
    public static Pokemon Diglett;
    public static Pokemon Dugtrio;
    public static Pokemon Meowth;
    public static Pokemon Persian;
    public static Pokemon Psyduck;
    public static Pokemon Golduck;
    public static Pokemon Mankey;
    public static Pokemon Primeape;
    public static Pokemon Growlithe;
    public static Pokemon Arcanine;
    public static Pokemon Poliwag;
    public static Pokemon Poliwhirl;
    public static Pokemon Poliwrath;
    public static Pokemon Abra;
    public static Pokemon Kadabra;
    public static Pokemon Alakazam;
    public static Pokemon Machop;
    public static Pokemon Machoke;
    public static Pokemon Machamp;
    public static Pokemon Bellsprout;
    public static Pokemon Weepinbell;
    public static Pokemon Victreebel;
    public static Pokemon Tentacool;
    public static Pokemon Tentacruel;
    public static Pokemon Geodude;
    public static Pokemon Graveler;
    public static Pokemon Golem;
    public static Pokemon Ponyta;
    public static Pokemon Rapidash;
    public static Pokemon Slowpoke;
    public static Pokemon Slowbro;
    public static Pokemon Magnemite;
    public static Pokemon Magneton;
    public static Pokemon Farfetchd;
    public static Pokemon Doduo;
    public static Pokemon Dodrio;
    public static Pokemon Seel;
    public static Pokemon Dewgong;
    public static Pokemon Grimer;
    public static Pokemon Muk;
    public static Pokemon Shellder;
    public static Pokemon Cloyster;
    public static Pokemon Gastly;
    public static Pokemon Haunter;
    public static Pokemon Gengar;
    public static Pokemon Onix;
    public static Pokemon Drowzee;
    public static Pokemon Hypno;
    public static Pokemon Krabby;
    public static Pokemon Kingler;
    public static Pokemon Voltorb;
    public static Pokemon Electrode;
    public static Pokemon Exeggcute;
    public static Pokemon Exeggutor;
    public static Pokemon Cubone;
    public static Pokemon Marowak;
    public static Pokemon Hitmonlee;
    public static Pokemon Hitmonchan;
    public static Pokemon Lickitung;
    public static Pokemon Koffing;
    public static Pokemon Rhyhorn;
    public static Pokemon Rhydon;
    public static Pokemon Chansey;
    public static Pokemon Tangela;
    public static Pokemon Kangaskhan;
    public static Pokemon Horsea;
    public static Pokemon Seadra;
    public static Pokemon Goldeen;
    public static Pokemon Seaking;
    public static Pokemon Staryu;
    public static Pokemon Starmie;
    public static Pokemon Mr_Mime;
    public static Pokemon Scyther;
    public static Pokemon Jynx;
    public static Pokemon Electabuzz;
    public static Pokemon Magmar;
    public static Pokemon Pinsir;
    public static Pokemon Tauros;
    public static Pokemon Magikarp;
    public static Pokemon Gyarados;
    public static Pokemon Lapras;
    public static Pokemon Ditto;
    public static Pokemon Eevee;
    public static Pokemon Vaporeon;
    public static Pokemon Jolteon;
    public static Pokemon Flareon;
    public static Pokemon Porygon;
    public static Pokemon Omanyte;
    public static Pokemon Omastar;
    public static Pokemon Kabuto;
    public static Pokemon Kabutops;
    public static Pokemon Aerodactyl;
    public static Pokemon Snorlax;
    public static Pokemon Articuno;
    public static Pokemon Zapdos;
    public static Pokemon Moltres;
    public static Pokemon Dratini;
    public static Pokemon Dragonair;
    public static Pokemon Dragonite;
    public static Pokemon Mewtwo;
    public static Pokemon Mew;
    public static Pokemon[] pokeList = new Pokemon[]{Bulbasaur, Ivysaur, Venusaur, Charmander, Charmeleon, Charizard, Squirtle, Wartortle, Blastoise, Caterpie, Metapod, Butterfree, Weedle, Kakuna, Beedrill, Pidgey, Pidgeotto, Pidgeot, Rattata, Raticate, Spearow, Fearow, Ekans, Arbok, Pikachu, Raichu, Sandshrew, Sandslash, NidoranF, Nidorina, Nidoqueen, NidoranM, Nidorino, Nidoking, Clefairy, Clefable, Vulpix, Ninetales, Jigglypuff, Wigglytuff, Zubat, Golbat, Oddish, Gloom, Vileplume, Paras, Parasect, Venonat, Venomoth, Diglett, Dugtrio, Meowth, Persian, Psyduck, Golduck, Mankey, Primeape, Growlithe, Arcanine, Poliwag, Poliwhirl, Poliwrath, Abra, Kadabra, Alakazam, Machop, Machoke, Machamp, Bellsprout, Weepinbell, Victreebel, Tentacool, Tentacruel, Geodude, Graveler, Golem, Ponyta, Rapidash, Slowpoke, Slowbro, Magnemite, Magneton, Farfetchd, Doduo, Dodrio, Seel, Dewgong, Grimer, Muk, Shellder, Cloyster, Gastly, Haunter, Gengar, Onix, Drowzee, Hypno, Krabby, Kingler, Voltorb, Electrode, Exeggcute, Exeggutor, Cubone, Marowak, Hitmonlee, Hitmonchan, Lickitung, Koffing, Rhyhorn, Rhydon, Chansey, Tangela, Kangaskhan, Horsea, Seadra, Goldeen, Seaking, Staryu, Starmie, Mr_Mime, Scyther, Jynx, Electabuzz, Magmar, Pinsir, Tauros, Magikarp, Gyarados, Lapras, Ditto, Eevee, Vaporeon, Jolteon, Flareon, Porygon, Omanyte, Omastar, Kabuto, Kabutops, Aerodactyl, Snorlax, Articuno, Zapdos, Moltres, Dratini, Dragonair, Dragonite, Mewtwo, Mew};
    public static Type[] types = {Grass,Rock,Ice,Dragon,Dark,Psychic,Bug,Flying,Steel,Fire,Fighting,Ground,Ghost,Poison,Water,Fairy,Electric,Normal};
    public static void main(String[] args) throws MalformedURLException {
        Bulbasaur = new Pokemon("Bulbasaur", 100, new int[]{15, 15, 15, 15, 15}, 45, 49, 49, 65, 65, 45, new Type[]{Grass}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/bulbasaur.png");
        Ivysaur = new Pokemon("Ivysaur", 100, new int[]{15, 15, 15, 15, 15}, 60, 62, 63, 80, 80, 60, new Type[]{Grass, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/ivysaur.png");
        Venusaur = new Pokemon("Venusaur", 100, new int[]{15, 15, 15, 15, 15}, 80, 82, 83, 100, 100, 80, new Type[]{Grass, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/venusaur.png");
        Charmander = new Pokemon("Charmander", 100, new int[]{15, 15, 15, 15, 15}, 39, 52, 43, 60, 50, 65, new Type[]{Fire}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/venusaur-mega.png");
        Charmeleon = new Pokemon("Charmeleon", 100, new int[]{15, 15, 15, 15, 15}, 58, 64, 58, 80, 65, 80, new Type[]{Fire}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/charmander.png");
        Charizard = new Pokemon("Charizard", 100, new int[]{15, 15, 15, 15, 15}, 78, 84, 78, 109, 85, 100, new Type[]{Fire, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/charmeleon.png");
        Squirtle = new Pokemon("Squirtle", 100, new int[]{15, 15, 15, 15, 15}, 44, 48, 65, 50, 64, 43, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/charizard.png");
        Wartortle = new Pokemon("Wartortle", 100, new int[]{15, 15, 15, 15, 15}, 59, 63, 80, 65, 80, 58, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/charizard-mega-x.png");
        Blastoise = new Pokemon("Blastoise", 100, new int[]{15, 15, 15, 15, 15}, 79, 83, 100, 85, 105, 78, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/charizard-mega-y.png");
        Caterpie = new Pokemon("Caterpie", 100, new int[]{15, 15, 15, 15, 15}, 45, 30, 35, 20, 20, 45, new Type[]{Bug}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/squirtle.png");
        Metapod = new Pokemon("Metapod", 100, new int[]{15, 15, 15, 15, 15}, 50, 20, 55, 25, 25, 30, new Type[]{Bug}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/wartortle.png");
        Butterfree = new Pokemon("Butterfree", 100, new int[]{15, 15, 15, 15, 15}, 60, 45, 50, 90, 80, 70, new Type[]{Bug, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/blastoise.png");
        Weedle = new Pokemon("Weedle", 100, new int[]{15, 15, 15, 15, 15}, 40, 35, 30, 20, 20, 50, new Type[]{Bug, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/blastoise-mega.png");
        Kakuna = new Pokemon("Kakuna", 100, new int[]{15, 15, 15, 15, 15}, 45, 25, 50, 25, 25, 35, new Type[]{Bug, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/caterpie.png");
        Beedrill = new Pokemon("Beedrill", 100, new int[]{15, 15, 15, 15, 15}, 65, 90, 40, 45, 80, 75, new Type[]{Bug, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/metapod.png");
        Pidgey = new Pokemon("Pidgey", 100, new int[]{15, 15, 15, 15, 15}, 40, 45, 40, 35, 35, 56, new Type[]{Normal, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/butterfree.png");
        Pidgeotto = new Pokemon("Pidgeotto", 100, new int[]{15, 15, 15, 15, 15}, 63, 60, 55, 50, 50, 71, new Type[]{Normal, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/weedle.png");
        Pidgeot = new Pokemon("Pidgeot", 100, new int[]{15, 15, 15, 15, 15}, 83, 80, 75, 70, 70, 101, new Type[]{Normal, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/kakuna.png");
        Rattata = new Pokemon("Rattata", 100, new int[]{15, 15, 15, 15, 15}, 30, 56, 35, 25, 35, 72, new Type[]{Normal}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/beedrill.png");
        Raticate = new Pokemon("Raticate", 100, new int[]{15, 15, 15, 15, 15}, 55, 81, 60, 50, 70, 97, new Type[]{Normal}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/beedrill-mega.png");
        Spearow = new Pokemon("Spearow", 100, new int[]{15, 15, 15, 15, 15}, 40, 60, 30, 31, 31, 70, new Type[]{Normal, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/pidgey.png");
        Fearow = new Pokemon("Fearow", 100, new int[]{15, 15, 15, 15, 15}, 65, 90, 65, 61, 61, 100, new Type[]{Normal, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/pidgeotto.png");
        Ekans = new Pokemon("Ekans", 100, new int[]{15, 15, 15, 15, 15}, 35, 60, 44, 40, 54, 55, new Type[]{Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/pidgeot.png");
        Arbok = new Pokemon("Arbok", 100, new int[]{15, 15, 15, 15, 15}, 60, 95, 69, 65, 79, 80, new Type[]{Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/pidgeot-mega.png");
        Pikachu = new Pokemon("Pikachu", 100, new int[]{15, 15, 15, 15, 15}, 35, 55, 40, 50, 50, 90, new Type[]{Electric}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/rattata.png");
        Raichu = new Pokemon("Raichu", 100, new int[]{15, 15, 15, 15, 15}, 60, 90, 55, 90, 80, 110, new Type[]{Electric}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/rattata-alolan.png");
        Sandshrew = new Pokemon("Sandshrew", 100, new int[]{15, 15, 15, 15, 15}, 50, 75, 85, 20, 30, 40, new Type[]{Ground}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/raticate.png");
        Sandslash = new Pokemon("Sandslash", 100, new int[]{15, 15, 15, 15, 15}, 75, 100, 110, 45, 55, 65, new Type[]{Ground}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/raticate-alolan.png");
        NidoranF = new Pokemon("Nidoran♀", 100, new int[]{15, 15, 15, 15, 15}, 55, 47, 52, 40, 40, 41, new Type[]{Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/spearow.png");
        Nidorina = new Pokemon("Nidorina", 100, new int[]{15, 15, 15, 15, 15}, 70, 62, 67, 55, 55, 56, new Type[]{Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/fearow.png");
        Nidoqueen = new Pokemon("Nidoqueen", 100, new int[]{15, 15, 15, 15, 15}, 90, 92, 87, 75, 85, 76, new Type[]{Poison, Ground}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/ekans.png");
        NidoranM = new Pokemon("Nidoran♂", 100, new int[]{15, 15, 15, 15, 15}, 46, 57, 40, 40, 40, 50, new Type[]{Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/arbok.png");
        Nidorino = new Pokemon("Nidorino", 100, new int[]{15, 15, 15, 15, 15}, 61, 72, 57, 55, 55, 65, new Type[]{Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/pikachu.png");
        Nidoking = new Pokemon("Nidoking", 100, new int[]{15, 15, 15, 15, 15}, 81, 102, 77, 85, 75, 85, new Type[]{Poison, Ground}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/pikachu-lets-go.png");
        Clefairy = new Pokemon("Clefairy", 100, new int[]{15, 15, 15, 15, 15}, 70, 45, 48, 60, 65, 35, new Type[]{Fairy}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/raichu.png");
        Clefable = new Pokemon("Clefable", 100, new int[]{15, 15, 15, 15, 15}, 95, 70, 73, 95, 90, 60, new Type[]{Fairy}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/raichu-alolan.png");
        Vulpix = new Pokemon("Vulpix", 100, new int[]{15, 15, 15, 15, 15}, 38, 41, 40, 50, 65, 65, new Type[]{Fire}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/sandshrew.png");
        Ninetales = new Pokemon("Ninetales", 100, new int[]{15, 15, 15, 15, 15}, 73, 76, 75, 81, 100, 100, new Type[]{Fire}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/sandshrew-alolan.png");
        Jigglypuff = new Pokemon("Jigglypuff", 100, new int[]{15, 15, 15, 15, 15}, 115, 45, 20, 45, 25, 20, new Type[]{Normal, Fairy}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/sandslash.png");
        Wigglytuff = new Pokemon("Wigglytuff", 100, new int[]{15, 15, 15, 15, 15}, 140, 70, 45, 85, 50, 45, new Type[]{Normal, Fairy}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/sandslash-alolan.png");
        Zubat = new Pokemon("Zubat", 100, new int[]{15, 15, 15, 15, 15}, 40, 45, 35, 30, 40, 55, new Type[]{Poison, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/nidoran-f.png");
        Golbat = new Pokemon("Golbat", 100, new int[]{15, 15, 15, 15, 15}, 75, 80, 70, 65, 75, 90, new Type[]{Poison, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/nidorina.png");
        Oddish = new Pokemon("Oddish", 100, new int[]{15, 15, 15, 15, 15}, 45, 50, 55, 75, 65, 30, new Type[]{Grass, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/nidoqueen.png");
        Gloom = new Pokemon("Gloom", 100, new int[]{15, 15, 15, 15, 15}, 60, 65, 70, 85, 75, 40, new Type[]{Grass, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/nidoran-m.png");
        Vileplume = new Pokemon("Vileplume", 100, new int[]{15, 15, 15, 15, 15}, 75, 80, 85, 110, 90, 50, new Type[]{Grass, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/nidorino.png");
        Paras = new Pokemon("Paras", 100, new int[]{15, 15, 15, 15, 15}, 35, 70, 55, 45, 55, 25, new Type[]{Bug, Grass}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/nidoking.png");
        Parasect = new Pokemon("Parasect", 100, new int[]{15, 15, 15, 15, 15}, 60, 95, 80, 60, 80, 30, new Type[]{Bug, Grass}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/clefairy.png");
        Venonat = new Pokemon("Venonat", 100, new int[]{15, 15, 15, 15, 15}, 60, 55, 50, 40, 55, 45, new Type[]{Bug, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/clefable.png");
        Venomoth = new Pokemon("Venomoth", 100, new int[]{15, 15, 15, 15, 15}, 70, 65, 60, 90, 75, 90, new Type[]{Bug, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/vulpix.png");
        Diglett = new Pokemon("Diglett", 100, new int[]{15, 15, 15, 15, 15}, 10, 55, 25, 35, 45, 95, new Type[]{Ground}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/vulpix-alolan.png");
        Dugtrio = new Pokemon("Dugtrio", 100, new int[]{15, 15, 15, 15, 15}, 35, 100, 50, 50, 70, 120, new Type[]{Ground}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/ninetales.png");
        Meowth = new Pokemon("Meowth", 100, new int[]{15, 15, 15, 15, 15}, 40, 45, 35, 40, 40, 90, new Type[]{Normal}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/ninetales-alolan.png");
        Persian = new Pokemon("Persian", 100, new int[]{15, 15, 15, 15, 15}, 65, 70, 60, 65, 65, 115, new Type[]{Normal}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/jigglypuff.png");
        Psyduck = new Pokemon("Psyduck", 100, new int[]{15, 15, 15, 15, 15}, 50, 52, 48, 65, 50, 55, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/wigglytuff.png");
        Golduck = new Pokemon("Golduck", 100, new int[]{15, 15, 15, 15, 15}, 80, 82, 78, 95, 80, 85, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/zubat.png");
        Mankey = new Pokemon("Mankey", 100, new int[]{15, 15, 15, 15, 15}, 40, 80, 35, 35, 45, 70, new Type[]{Fighting}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/golbat.png");
        Primeape = new Pokemon("Primeape", 100, new int[]{15, 15, 15, 15, 15}, 65, 105, 60, 60, 70, 95, new Type[]{Fighting}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/oddish.png");
        Growlithe = new Pokemon("Growlithe", 100, new int[]{15, 15, 15, 15, 15}, 55, 70, 45, 70, 50, 60, new Type[]{Fire}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/gloom.png");
        Arcanine = new Pokemon("Arcanine", 100, new int[]{15, 15, 15, 15, 15}, 90, 110, 80, 100, 80, 95, new Type[]{Fire}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/vileplume.png");
        Poliwag = new Pokemon("Poliwag", 100, new int[]{15, 15, 15, 15, 15}, 40, 50, 40, 40, 40, 90, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/paras.png");
        Poliwhirl = new Pokemon("Poliwhirl", 100, new int[]{15, 15, 15, 15, 15}, 65, 65, 65, 50, 50, 90, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/parasect.png");
        Poliwrath = new Pokemon("Poliwrath", 100, new int[]{15, 15, 15, 15, 15}, 90, 95, 95, 70, 90, 70, new Type[]{Water, Fighting}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/venonat.png");
        Abra = new Pokemon("Abra", 100, new int[]{15, 15, 15, 15, 15}, 25, 20, 15, 105, 55, 90, new Type[]{Psychic}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/venomoth.png");
        Kadabra = new Pokemon("Kadabra", 100, new int[]{15, 15, 15, 15, 15}, 40, 35, 30, 120, 70, 105, new Type[]{Psychic}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/diglett.png");
        Alakazam = new Pokemon("Alakazam", 100, new int[]{15, 15, 15, 15, 15}, 55, 50, 45, 135, 95, 120, new Type[]{Psychic}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/diglett-alolan.png");
        Machop = new Pokemon("Machop", 100, new int[]{15, 15, 15, 15, 15}, 70, 80, 50, 35, 35, 35, new Type[]{Fighting}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/dugtrio.png");
        Machoke = new Pokemon("Machoke", 100, new int[]{15, 15, 15, 15, 15}, 80, 100, 70, 50, 60, 45, new Type[]{Fighting}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/dugtrio-alolan.png");
        Machamp = new Pokemon("Machamp", 100, new int[]{15, 15, 15, 15, 15}, 90, 130, 80, 65, 85, 55, new Type[]{Fighting}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/meowth.png");
        Bellsprout = new Pokemon("Bellsprout", 100, new int[]{15, 15, 15, 15, 15}, 50, 75, 35, 70, 30, 40, new Type[]{Grass, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/meowth-alolan.png");
        Weepinbell = new Pokemon("Weepinbell", 100, new int[]{15, 15, 15, 15, 15}, 65, 90, 50, 85, 45, 55, new Type[]{Grass, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/meowth-galarian.png");
        Victreebel = new Pokemon("Victreebel", 100, new int[]{15, 15, 15, 15, 15}, 80, 105, 65, 100, 70, 70, new Type[]{Grass, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/persian.png");
        Tentacool = new Pokemon("Tentacool", 100, new int[]{15, 15, 15, 15, 15}, 40, 40, 35, 50, 100, 70, new Type[]{Water, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/persian-alolan.png");
        Tentacruel = new Pokemon("Tentacruel", 100, new int[]{15, 15, 15, 15, 15}, 80, 70, 65, 80, 120, 100, new Type[]{Water, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/psyduck.png");
        Geodude = new Pokemon("Geodude", 100, new int[]{15, 15, 15, 15, 15}, 40, 80, 100, 30, 30, 20, new Type[]{Rock, Ground}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/golduck.png");
        Graveler = new Pokemon("Graveler", 100, new int[]{15, 15, 15, 15, 15}, 55, 95, 115, 45, 45, 35, new Type[]{Rock, Ground}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/mankey.png");
        Golem = new Pokemon("Golem", 100, new int[]{15, 15, 15, 15, 15}, 80, 120, 130, 55, 65, 45, new Type[]{Rock, Ground}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/primeape.png");
        Ponyta = new Pokemon("Ponyta", 100, new int[]{15, 15, 15, 15, 15}, 50, 85, 55, 65, 65, 90, new Type[]{Fire}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/growlithe.png");
        Rapidash = new Pokemon("Rapidash", 100, new int[]{15, 15, 15, 15, 15}, 65, 100, 70, 80, 80, 105, new Type[]{Fire}, new Move[]{}, "https://img.pokemondb.net/sprites/scarlet-violet/icon/growlithe-hisuian.png");
        Slowpoke = new Pokemon("Slowpoke", 100, new int[]{15, 15, 15, 15, 15}, 90, 65, 65, 40, 40, 15, new Type[]{Water, Psychic}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/arcanine.png");
        Slowbro = new Pokemon("Slowbro", 100, new int[]{15, 15, 15, 15, 15}, 95, 75, 110, 100, 80, 30, new Type[]{Water, Psychic}, new Move[]{}, "https://img.pokemondb.net/sprites/scarlet-violet/icon/arcanine-hisuian.png");
        Magnemite = new Pokemon("Magnemite", 100, new int[]{15, 15, 15, 15, 15}, 25, 35, 70, 95, 55, 45, new Type[]{Electric, Steel}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/poliwag.png");
        Magneton = new Pokemon("Magneton", 100, new int[]{15, 15, 15, 15, 15}, 50, 60, 95, 120, 70, 70, new Type[]{Electric, Steel}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/poliwhirl.png");
        Farfetchd = new Pokemon("Farfetch'd", 100, new int[]{15, 15, 15, 15, 15}, 52, 90, 55, 58, 62, 60, new Type[]{Normal, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/poliwrath.png");
        Doduo = new Pokemon("Doduo", 100, new int[]{15, 15, 15, 15, 15}, 35, 85, 45, 35, 35, 75, new Type[]{Normal, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/abra.png");
        Dodrio = new Pokemon("Dodrio", 100, new int[]{15, 15, 15, 15, 15}, 60, 110, 70, 60, 60, 110, new Type[]{Normal, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/kadabra.png");
        Seel = new Pokemon("Seel", 100, new int[]{15, 15, 15, 15, 15}, 65, 45, 55, 45, 70, 45, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/alakazam.png");
        Dewgong = new Pokemon("Dewgong", 100, new int[]{15, 15, 15, 15, 15}, 90, 70, 80, 70, 95, 70, new Type[]{Water, Ice}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/alakazam-mega.png");
        Grimer = new Pokemon("Grimer", 100, new int[]{15, 15, 15, 15, 15}, 80, 80, 50, 40, 50, 25, new Type[]{Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/machop.png");
        Muk = new Pokemon("Muk", 100, new int[]{15, 15, 15, 15, 15}, 105, 105, 75, 65, 100, 50, new Type[]{Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/machoke.png");
        Shellder = new Pokemon("Shellder", 100, new int[]{15, 15, 15, 15, 15}, 30, 65, 100, 45, 25, 40, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/machamp.png");
        Cloyster = new Pokemon("Cloyster", 100, new int[]{15, 15, 15, 15, 15}, 50, 95, 180, 85, 45, 70, new Type[]{Water, Ice}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/bellsprout.png");
        Gastly = new Pokemon("Gastly", 100, new int[]{15, 15, 15, 15, 15}, 30, 35, 30, 100, 35, 80, new Type[]{Ghost, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/weepinbell.png");
        Haunter = new Pokemon("Haunter", 100, new int[]{15, 15, 15, 15, 15}, 45, 50, 45, 115, 55, 95, new Type[]{Ghost, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/victreebel.png");
        Gengar = new Pokemon("Gengar", 100, new int[]{15, 15, 15, 15, 15}, 60, 65, 60, 130, 75, 110, new Type[]{Ghost, Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/tentacool.png");
        Onix = new Pokemon("Onix", 100, new int[]{15, 15, 15, 15, 15}, 35, 45, 160, 30, 45, 70, new Type[]{Rock, Ground}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/tentacruel.png");
        Drowzee = new Pokemon("Drowzee", 100, new int[]{15, 15, 15, 15, 15}, 60, 48, 45, 43, 90, 42, new Type[]{Psychic}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/geodude.png");
        Hypno = new Pokemon("Hypno", 100, new int[]{15, 15, 15, 15, 15}, 85, 73, 70, 73, 115, 67, new Type[]{Psychic}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/geodude-alolan.png");
        Krabby = new Pokemon("Krabby", 100, new int[]{15, 15, 15, 15, 15}, 30, 105, 90, 25, 25, 50, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/graveler.png");
        Kingler = new Pokemon("Kingler", 100, new int[]{15, 15, 15, 15, 15}, 55, 130, 115, 50, 50, 75, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/graveler-alolan.png");
        Voltorb = new Pokemon("Voltorb", 100, new int[]{15, 15, 15, 15, 15}, 40, 30, 50, 55, 55, 100, new Type[]{Electric}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/golem.png");
        Electrode = new Pokemon("Electrode", 100, new int[]{15, 15, 15, 15, 15}, 60, 50, 70, 80, 80, 150, new Type[]{Electric}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/golem-alolan.png");
        Exeggcute = new Pokemon("Exeggcute", 100, new int[]{15, 15, 15, 15, 15}, 60, 40, 80, 60, 45, 40, new Type[]{Grass, Psychic}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/ponyta.png");
        Exeggutor = new Pokemon("Exeggutor", 100, new int[]{15, 15, 15, 15, 15}, 95, 95, 85, 125, 75, 55, new Type[]{Grass, Psychic}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/ponyta-galarian.png");
        Cubone = new Pokemon("Cubone", 100, new int[]{15, 15, 15, 15, 15}, 50, 50, 95, 40, 50, 35, new Type[]{Ground}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/rapidash.png");
        Marowak = new Pokemon("Marowak", 100, new int[]{15, 15, 15, 15, 15}, 60, 80, 110, 50, 80, 45, new Type[]{Ground}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/rapidash-galarian.png");
        Hitmonlee = new Pokemon("Hitmonlee", 100, new int[]{15, 15, 15, 15, 15}, 50, 120, 53, 35, 110, 87, new Type[]{Fighting}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/slowpoke.png");
        Hitmonchan = new Pokemon("Hitmonchan", 100, new int[]{15, 15, 15, 15, 15}, 50, 105, 79, 35, 110, 76, new Type[]{Fighting}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/slowpoke-galarian.png");
        Lickitung = new Pokemon("Lickitung", 100, new int[]{15, 15, 15, 15, 15}, 90, 55, 75, 60, 75, 30, new Type[]{Normal}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/slowbro.png");
        Koffing = new Pokemon("Koffing", 100, new int[]{15, 15, 15, 15, 15}, 40, 65, 95, 60, 45, 35, new Type[]{Poison}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/slowbro-mega.png");
        Rhyhorn = new Pokemon("Rhyhorn", 100, new int[]{15, 15, 15, 15, 15}, 80, 85, 95, 30, 30, 25, new Type[]{Ground, Rock}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/slowbro-galarian.png");
        Rhydon = new Pokemon("Rhydon", 100, new int[]{15, 15, 15, 15, 15}, 105, 130, 120, 45, 45, 40, new Type[]{Ground, Rock}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/magnemite.png");
        Chansey = new Pokemon("Chansey", 100, new int[]{15, 15, 15, 15, 15}, 250, 5, 5, 35, 105, 50, new Type[]{Normal}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/magneton.png");
        Tangela = new Pokemon("Tangela", 100, new int[]{15, 15, 15, 15, 15}, 65, 55, 115, 100, 40, 60, new Type[]{Grass}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/farfetchd.png");
        Kangaskhan = new Pokemon("Kangaskhan", 100, new int[]{15, 15, 15, 15, 15}, 105, 95, 80, 40, 80, 90, new Type[]{Normal}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/farfetchd-galarian.png");
        Horsea = new Pokemon("Horsea", 100, new int[]{15, 15, 15, 15, 15}, 30, 40, 70, 70, 25, 60, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/doduo.png");
        Seadra = new Pokemon("Seadra", 100, new int[]{15, 15, 15, 15, 15}, 55, 65, 95, 95, 45, 85, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/dodrio.png");
        Goldeen = new Pokemon("Goldeen", 100, new int[]{15, 15, 15, 15, 15}, 45, 67, 60, 35, 50, 63, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/seel.png");
        Seaking = new Pokemon("Seaking", 100, new int[]{15, 15, 15, 15, 15}, 80, 92, 65, 65, 80, 68, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/dewgong.png");
        Staryu = new Pokemon("Staryu", 100, new int[]{15, 15, 15, 15, 15}, 30, 45, 55, 70, 55, 85, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/grimer.png");
        Starmie = new Pokemon("Starmie", 100, new int[]{15, 15, 15, 15, 15}, 60, 75, 85, 100, 85, 115, new Type[]{Water, Psychic}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/grimer-alolan.png");
        Mr_Mime = new Pokemon("Mr. Mime", 100, new int[]{15, 15, 15, 15, 15}, 40, 45, 65, 100, 120, 90, new Type[]{Psychic, Fairy}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/muk.png");
        Scyther = new Pokemon("Scyther", 100, new int[]{15, 15, 15, 15, 15}, 70, 110, 80, 55, 80, 105, new Type[]{Bug, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/muk-alolan.png");
        Jynx = new Pokemon("Jynx", 100, new int[]{15, 15, 15, 15, 15}, 65, 50, 35, 115, 95, 95, new Type[]{Ice, Psychic}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/shellder.png");
        Electabuzz = new Pokemon("Electabuzz", 100, new int[]{15, 15, 15, 15, 15}, 65, 83, 57, 95, 85, 105, new Type[]{Electric}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/cloyster.png");
        Magmar = new Pokemon("Magmar", 100, new int[]{15, 15, 15, 15, 15}, 65, 95, 57, 100, 85, 93, new Type[]{Fire}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/gastly.png");
        Pinsir = new Pokemon("Pinsir", 100, new int[]{15, 15, 15, 15, 15}, 65, 125, 100, 55, 70, 85, new Type[]{Bug}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/haunter.png");
        Tauros = new Pokemon("Tauros", 100, new int[]{15, 15, 15, 15, 15}, 75, 100, 95, 40, 70, 110, new Type[]{Normal}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/gengar.png");
        Magikarp = new Pokemon("Magikarp", 100, new int[]{15, 15, 15, 15, 15}, 20, 10, 55, 15, 20, 80, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/gengar-mega.png");
        Gyarados = new Pokemon("Gyarados", 100, new int[]{15, 15, 15, 15, 15}, 95, 125, 79, 60, 100, 81, new Type[]{Water, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/onix.png");
        Lapras = new Pokemon("Lapras", 100, new int[]{15, 15, 15, 15, 15}, 130, 85, 80, 85, 95, 60, new Type[]{Water, Ice}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/drowzee.png");
        Ditto = new Pokemon("Ditto", 100, new int[]{15, 15, 15, 15, 15}, 48, 48, 48, 48, 48, 48, new Type[]{Normal}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/hypno.png");
        Eevee = new Pokemon("Eevee", 100, new int[]{15, 15, 15, 15, 15}, 55, 55, 50, 45, 65, 55, new Type[]{Normal}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/krabby.png");
        Vaporeon = new Pokemon("Vaporeon", 100, new int[]{15, 15, 15, 15, 15}, 130, 65, 60, 110, 95, 65, new Type[]{Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/kingler.png");
        Jolteon = new Pokemon("Jolteon", 100, new int[]{15, 15, 15, 15, 15}, 65, 65, 60, 110, 95, 130, new Type[]{Electric}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/voltorb.png");
        Flareon = new Pokemon("Flareon", 100, new int[]{15, 15, 15, 15, 15}, 65, 130, 60, 95, 110, 65, new Type[]{Fire}, new Move[]{}, "https://img.pokemondb.net/sprites/scarlet-violet/icon/voltorb-hisuian.png");
        Porygon = new Pokemon("Porygon", 100, new int[]{15, 15, 15, 15, 15}, 65, 60, 70, 85, 75, 40, new Type[]{Normal}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/electrode.png");
        Omanyte = new Pokemon("Omanyte", 100, new int[]{15, 15, 15, 15, 15}, 35, 40, 100, 90, 55, 35, new Type[]{Rock, Water}, new Move[]{}, "https://img.pokemondb.net/sprites/scarlet-violet/icon/electrode-hisuian.png");
        Omastar = new Pokemon("Omastar", 100, new int[]{15, 15, 15, 15, 15}, 70, 60, 125, 115, 70, 55, new Type[]{Rock, Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/exeggcute.png");
        Kabuto = new Pokemon("Kabuto", 100, new int[]{15, 15, 15, 15, 15}, 30, 80, 90, 55, 45, 55, new Type[]{Rock, Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/exeggutor.png");
        Kabutops = new Pokemon("Kabutops", 100, new int[]{15, 15, 15, 15, 15}, 60, 115, 105, 65, 70, 80, new Type[]{Rock, Water}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/exeggutor-alolan.png");
        Aerodactyl = new Pokemon("Aerodactyl", 100, new int[]{15, 15, 15, 15, 15}, 80, 105, 65, 60, 75, 130, new Type[]{Rock, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/cubone.png");
        Snorlax = new Pokemon("Snorlax", 100, new int[]{15, 15, 15, 15, 15}, 160, 110, 65, 65, 110, 30, new Type[]{Normal}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/marowak.png");
        Articuno = new Pokemon("Articuno", 100, new int[]{15, 15, 15, 15, 15}, 90, 85, 100, 95, 125, 85, new Type[]{Ice, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/marowak-alolan.png");
        Zapdos = new Pokemon("Zapdos", 100, new int[]{15, 15, 15, 15, 15}, 90, 90, 85, 125, 90, 100, new Type[]{Electric, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/hitmonlee.png");
        Moltres = new Pokemon("Moltres", 100, new int[]{15, 15, 15, 15, 15}, 90, 100, 90, 125, 85, 90, new Type[]{Fire, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/hitmonchan.png");
        Dratini = new Pokemon("Dratini", 100, new int[]{15, 15, 15, 15, 15}, 41, 64, 45, 50, 50, 50, new Type[]{Dragon}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/lickitung.png");
        Dragonair = new Pokemon("Dragonair", 100, new int[]{15, 15, 15, 15, 15}, 61, 84, 65, 70, 70, 70, new Type[]{Dragon}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/koffing.png");
        Dragonite = new Pokemon("Dragonite", 100, new int[]{15, 15, 15, 15, 15}, 91, 134, 95, 100, 100, 80, new Type[]{Dragon, Flying}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/weezing.png");
        Mewtwo = new Pokemon("Mewtwo", 100, new int[]{15, 15, 15, 15, 15}, 106, 110, 90, 154, 90, 130, new Type[]{Psychic}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/weezing-galarian.png");
        Mew = new Pokemon("Mew", 100, new int[]{15, 15, 15, 15, 15}, 100, 100, 100, 100, 100, 100, new Type[]{Psychic}, new Move[]{}, "https://img.pokemondb.net/sprites/sword-shield/icon/rhyhorn.png");

        Normal.setWeakness(new Type[]{Fighting});
        Normal.setTypeAdvantage(new Type[]{None});
        Fire.setWeakness(new Type[]{Water,Ground, Rock});
        Fire.setTypeAdvantage(new Type[]{Grass,Ice,Bug,Steel});
        Water.setWeakness(new Type[]{Grass, Electric});
        Water.setTypeAdvantage(new Type[]{Fire,Ground,Rock});
        Grass.setWeakness(new Type[]{Fire,Ice,Poison,Flying,Bug});
        Grass.setTypeAdvantage(new Type[]{Water,Ground,Rock});
        Electric.setWeakness(new Type[]{Ground});
        Electric.setTypeAdvantage(new Type[]{Water,Flying});
        Ice.setWeakness(new Type[]{Fire,Fighting,Rock,Steel});
        Ice.setTypeAdvantage(new Type[]{Grass,Ground,Flying,Dragon});
        Fighting.setWeakness(new Type[]{Psychic,Flying,Fairy});
        Fighting.setTypeAdvantage(new Type[]{Normal,Ice,Rock,Dark,Steel});
        Poison.setWeakness(new Type[]{Ground, Psychic});
        Poison.setTypeAdvantage(new Type[]{Grass,Fairy});
        Ground.setWeakness(new Type[]{Water,Grass,Ice});
        Ground.setTypeAdvantage(new Type[]{Fire,Electric,Poison,Rock,Steel});
        Flying.setWeakness(new Type[]{Electric,Rock,Ice});
        Flying.setTypeAdvantage(new Type[]{Grass,Fighting,Bug});
        Psychic.setWeakness(new Type[]{Bug,Ghost,Dark});
        Psychic.setTypeAdvantage(new Type[]{Fighting,Poison});
        Bug.setWeakness(new Type[]{Flying,Rock,Fire});
        Bug.setTypeAdvantage(new Type[]{Grass,Psychic,Dark});
        Rock.setWeakness(new Type[]{Water,Grass,Fighting,Ground,Steel});
        Rock.setTypeAdvantage(new Type[]{Fire,Ice,Flying,Bug});
        Ghost.setWeakness(new Type[]{Ghost,Dark});
        Ghost.setTypeAdvantage(new Type[]{Psychic, Ghost});
        Dragon.setWeakness(new Type[]{Ice,Dragon,Fairy});
        Dragon.setTypeAdvantage(new Type[]{Dragon});
        Dark.setWeakness(new Type[]{Fighting,Bug,Fairy});
        Dark.setTypeAdvantage(new Type[]{Psychic,Ghost});
        Steel.setWeakness(new Type[]{Fire,Fighting,Ground});
        Steel.setTypeAdvantage(new Type[]{Ice,Rock,Fairy});
        Fairy.setWeakness(new Type[]{Poison,Steel});
        Fairy.setTypeAdvantage(new Type[]{Fighting,Dragon,Dark});

        for(int i=0;i<18;i++) {
            System.out.println(types[i].getType() + " \nWeaknesses: " + types[i].getWeaknesses() + " \nAdvantages: " + types[i].getTypeAdvantages());
            System.out.println();
        }
        Type effChecker = new Type();
        System.out.println(effChecker.getEffectiveness(new Type[]{Grass},new Type[]{Water}));

        System.out.println("Squirtle HP: "+Squirtle.getHp());
        //ember.attack(charmander,squirtle);

        System.out.println("Squirtle HP: "+Squirtle.getHp());
        Battle battle = new Battle();
    }
}